#this is assumed

server:
 port: 8080
 
#spring:
 # profiles: 
  # active:
   #- "@profileActive"
   
   #will need to override credentials
   #url,username,password
   #inject enviornment variable into yml

spring:
  datasource:
    url: jdbc:postgresql://art-db.cxk7mmlgp26b.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    
    
    