server:
 port: 8080
 
spring:
  datasource:
    url: jdbc:postgresql://art-db.cxk7mmlgp26b.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true