server:
 port: 8080
 
#spring:
#  profiles: 
#   active:
#   - "@profileActive"

spring:
 datasource:
  url: art-db.cxk7mmlgp26b.us-east-1.rds.amazonaws.com
  username: postgres
  password: Password$
 jpa:
  database-platform: org.hibernate.dialect.PostgresSQLDialect
  hibernate:
   ddl-auto: validate